"""Exceptions used across the Archive. GIVEN — do not edit this file."""


class MalformedRecordError(Exception):
    """Raised when a CSV line does not contain exactly 5 fields.

    This is NOT the same as an invalid record. A malformed line cannot even
    be split into the five fields we expect, so there is nothing to validate.
    An invalid record splits fine but contains values we do not trust.
    """


class ArchiveError(Exception):
    """Base class for any other Archive problem you want to raise."""
