"""Provided tests — GIVEN. DO NOT EDIT THIS FILE.

These cover the obvious cases so you can check you have wired things up
correctly. They are NOT the grading suite. The hidden suite is larger and
tests the edges you have been warned about.

Passing these is necessary. It is not sufficient.

Run them with:    pytest tests/test_provided.py -v
"""

import os
import tempfile

import pytest

from archive.errors import MalformedRecordError
from archive.storage import parse_line, load_archive, save_archive
from archive.validation import (
    validate_id,
    validate_title,
    validate_city,
    validate_year,
    validate_condition,
    validate_record,
)
from archive.queries import count_before, find_by_city, oldest, cities_summary


# ---------------------------------------------------------------- fixtures

GOOD_RECORD = {
    "id": "MS001",
    "title": "Tarikh al-Sudan",
    "city": "Timbuktu",
    "year": "1655",
    "condition": "fragile",
}

SAMPLE = [
    {"id": "MS001", "title": "Tarikh al-Sudan", "city": "Timbuktu",
     "year": "1655", "condition": "fragile"},
    {"id": "MS002", "title": "Kitab al-Tara'if", "city": "Djenne",
     "year": "1590", "condition": "good"},
    {"id": "MS003", "title": "Risala fi'l-Nujum", "city": "Timbuktu",
     "year": "1548", "condition": "fragile"},
]


# --------------------------------------------------------------- validation

def test_validate_id_accepts_well_formed():
    assert validate_id("MS001")[0] is True


def test_validate_id_rejects_short():
    assert validate_id("MS1")[0] is False


def test_validate_title_accepts_normal():
    assert validate_title("Tarikh al-Sudan")[0] is True


def test_validate_title_rejects_empty():
    assert validate_title("")[0] is False


def test_validate_city_accepts_known():
    assert validate_city("Timbuktu")[0] is True


def test_validate_city_rejects_unknown():
    assert validate_city("Kano")[0] is False


def test_validate_year_accepts_normal():
    assert validate_year("1655")[0] is True


def test_validate_year_rejects_text():
    assert validate_year("c.1590")[0] is False


def test_validate_condition_accepts_fragile():
    assert validate_condition("fragile")[0] is True


def test_validate_condition_rejects_excellent():
    assert validate_condition("excellent")[0] is False


def test_validate_record_accepts_good_record():
    assert validate_record(GOOD_RECORD) == []


def test_validate_record_reports_a_reason_for_bad_year():
    bad = dict(GOOD_RECORD, year="2087")
    reasons = validate_record(bad)
    assert len(reasons) == 1


# ------------------------------------------------------------------ storage

def test_parse_line_splits_five_fields():
    got = parse_line("MS001,Tarikh al-Sudan,Timbuktu,1655,fragile")
    assert got["id"] == "MS001"
    assert got["title"] == "Tarikh al-Sudan"
    assert got["city"] == "Timbuktu"
    assert got["year"] == "1655"
    assert got["condition"] == "fragile"


def test_parse_line_raises_on_four_fields():
    with pytest.raises(MalformedRecordError):
        parse_line("MS008,Sharh al-Mukhtasar,Djenne,1644")


def test_load_archive_missing_file_returns_empty():
    records, rejected = load_archive("data/definitely_not_here.csv")
    assert records == []
    assert rejected == []


def test_load_archive_reads_the_clean_file():
    records, rejected = load_archive("data/archive.csv")
    assert len(records) == 20
    assert rejected == []


def test_save_then_load_round_trip():
    path = os.path.join(tempfile.mkdtemp(), "out.csv")
    save_archive(path, SAMPLE)
    records, rejected = load_archive(path)
    assert len(records) == 3
    assert rejected == []
    assert records[0]["title"] == "Tarikh al-Sudan"


# ------------------------------------------------------------------ queries

def test_count_before():
    assert count_before(SAMPLE, 1600) == 2


def test_find_by_city():
    assert len(find_by_city(SAMPLE, "Timbuktu")) == 2


def test_oldest():
    assert oldest(SAMPLE)["id"] == "MS003"


def test_oldest_of_empty_is_none():
    assert oldest([]) is None


def test_cities_summary():
    assert cities_summary(SAMPLE) == {"Timbuktu": 2, "Djenne": 1}
